project:
  type: website

website:
  title: "✈️"
  navbar:
    left:
      - href: trame.qmd
        text: Consigne de l'exercice
      - href: https://rplane-dashboard.kub.sspcloud.fr/
        text: Tableau de bord (version {{< fa brands r-project >}})

format:
  html:
    theme: cosmo
    toc: true
    code-link: true



